#!/usr/bin/env ruby

# CLI to retrieve AWS credentials in credential_process format.
# Ref: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

require 'aws/google'
require 'time'
require 'json'

google = ::Aws::CredentialProviderChain.new.resolve
credentials = google.credentials
output = {
  Version: 1,
  AccessKeyId: credentials.access_key_id,
  SecretAccessKey: credentials.secret_access_key,
  SessionToken: credentials.session_token,
  Expiration: Time.at(google.expiration.to_i).iso8601
}
puts output.to_json
