#!/usr/bin/env ruby
warn "\e[31m*** DEPRECATION NOTICE: The aws-google CLI is deprecated and will no longer auto-refresh credentials. Migrate to AWS IAM Identity Center. ***\e[0m"

# CLI to retrieve AWS credentials in credential_process format.
# Ref: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

require 'aws/google'
require 'time'
require 'json'

google = ::Aws::STS::Client.new.config.credentials
credentials = google.credentials
output = {
  Version: 1,
  AccessKeyId: credentials.access_key_id,
  SecretAccessKey: credentials.secret_access_key,
  SessionToken: credentials.session_token,
  Expiration: Time.at(google.expiration.to_i).iso8601
}
puts output.to_json
